class Employee
{
    int empo;
    String name;
    float sal:

    Employee({
        System.out.println("*****");
        empno = 101;
                name = "Aashish";
                sal = 5000f;

    }  
    void displayDetails(){
            System.out.println(empno+" | " + name+ " | " sal);
    }
    )
}

class Main
{
        public static void main(String[]args)
        {
       Employee empl = nem Employee();
       Employee emp2 = nem Employee();
       Employee emp3 = nem Employee();

       emp1.displayDetails();
       emp2.displayDetails();
       emp3.displayDetails();
        }
}